export const routes = {
  home: '/',
  auth: '/auth',
  login: '/auth/login',
  register: '/auth/register',
  reset: '/auth/reset_password',
  inbox: 'inbox',
  privacy: '/privacy',
  policy: '/policy',
  card: '/card',
  products: '/products',
  product: '/products/:id',
  productAdd: '/product/new',
  user: '/users/:id/products',
  chat: '/chats',
  message: '/chats/:id',
  me: '/me',
  saved: '/saved',
  search: '/search',
};